[[elements-lang]]
== Java Language Extensions

This chapter covers Java language extensions and features provided by _Elements_.

[[elements-lang-dsl]]
=== Domain Specific Languages (DSL)

_Elements_ provides 5 different domain-specific languages (DSL) that you can use to write concise, yet expressive code.
By statically importing the DSL language operators defined in the `org.cp.elements.lang.LangExtensions` class,
you can immediately write much more powerful code in fewer lines.

[[elements-lang-dsl-assertThat]]
==== `assertThat` operator

The `assertThat` operator and DSL enables developers to make assertions about the state of his or her running programs.

For instance, a developer can assert that an object reference is not `null`.

.AssertThat Not Null
[source,java]
[subs="verbatim,attributes"]
----
assertThat(objectReference).isNotNull();
----

The `assertThat` operator and DSL provided by _Elements_ is very similar in form and function to
https://assertj.github.io/doc/[AssertJ], and was partly inspired by AssertJ. However, Elements `assertThat` operator
and DSL focuses on the most common and useful assertions with more refined expressions.

NOTE: For complete assertion capabilities, we recommend developers use AssertJ.

Common assertions include, but are not limited to:

* `isAssignableTo(:Class<?>)` | `isInstanceOf(:Class<?>)`
* `isComparableTo(:Coparable<?>)` | `isNotComparableTo(:Comparable<?>)`
* `isEqualTo(:Object)` | `isNotEqualTo(:Object)`
* `isGreaterThan(..)`
* `isGreaterThanAndLessThan(..)`
* `isGreaterThanAndLessThanEqualTo(..)`
* `isGreaterThanEqualTo(..)`
* `isGreaterThanEqualToAndLessThan(..)`
* `isGreaterThanEqualToAndLessThanEqualTo(..)`
* `hasText()`
* `holdsLock(:Object)`
* `isNotBlank()`
* `isNotEmpty()` - Can be used for: Arrays, Collections, Iterables, Maps and Strings
* `isNotNull()`
* `isFalse()` | `isTrue()`
* `isLessThan(..)`
* `isLessThanOrGreaterThan(..)`
* `isLessThanOrGreaterThanEqualTo(..)`
* `isLessThanEqualTo(..)`
* `isLessThanEqualToOrGreaterThan(..)`
* `isLessThanEqualToOrGreaterThanEqualTo(..)`
* `isNull()` | `isNotNull()`
* `isSameAs(:Object)` | `isNotSameAs(:Object)`
* `isValid(:Predicate)`

In addition to the assertions listed above, the `assertThat` operator supports strongly-typed assertions
making it possible to do:

.Type-specific assertions
[source,java]
[subs="verbatim,attributes"]
----
Object user = //...

assertThat(user).isInstanceOf(User.class)
  .as(User.class)
  .isEqualTo(User.as("jonDoe"));
----

The assertion above is useful when the incoming object type is not known in advance. More specifically, developers
may assert specific properties of a typed object as well:

.Assertion extraction (mapping)
[source,java]
[subs="verbatim,attributes"]
----
Object user = //...

assertThat(user).isInstanceOf(User.class)
  .as(User.class)
  .map(User::getName)
  .isEqualTo("jonDoe");
----

Developers may customize the Exception message thrown from the assertion as well as throw custom Exceptions
when necessary:

.Custom Exception message
[source,java]
[subs="verbatim,attributes"]
----
Object user = //...

assertThat(user).isInstanceOf(User.class).as(User.class)
  .describedAs("Expected user of type [%s]", User.class.getName())
  .map(User::getName)
  .isEqualTo("jonDoe");
----

.Custom Exception
[source,java]
[subs="verbatim,attributes"]
----
Object user = //...

assertThat(user).isInstanceOf(User.class).as(User.class)
  .throwing(new UnauthorizedUser("User " + user + " is not authorized"))
  .map(User::getRole)
  .isEqualTo("Admin");
----

An assertion may be easily negated using `not()`, such as:

.Assertion negation
[source,java]
[subs="verbatim,attributes"]
----
assertThat(object).not().holdsLock();
----

Certain assertions conveniently provide named negation variants, such as:
`isNotEqualTo(:Object)` or `isNotSameAs(:Object)`. That is the following:

.Equivalent `isNotEqual(:Object)`
[source,java]
[subs="verbatim,attributes"]
----
assertThat(object).isNotEqualTo(anotherObject);
----

Is the same as:

.Equivalent `not().isEqualTo(:Object)`
[source,java]
[subs="verbatim,attributes"]
----
assertThat(object).not().isEqualTo(anotherObject);
----

Unlike Java assertions, Elements assertions can be enabled or disabled using a complex expression, expressed with a
custom `Condition` implementation.

.Conditional assertions
[source,java]
[subs="verbatim,attributes"]
----
Condition enabled = // ...

assertThat(object).when(enabled).isValid(:Predicate)
----

A `Condition` can be reused across assertions. Individual, or grouped assertions can each have custom `Conditions`
of your choosing.

1 last highlight with the `assertThat` operator is using the `isValid(:Predicate)` method. `isValid` accepts a
`Predicate` allowing for complex conditions to be expressed that cannot be easily expressed with the provided,
default operators, such as `isEqualTo(..)`.

For instance:

.Using `isValid(:Predicate)`
[source,java]
[subs="verbatim,attributes"]
----
Predicate<User> userPredicate = user -> session.getUser().equals(user);

userPredicate.andThen(user -> user.getRole().getName().equals("ADMIN"));
userPredicate.andThen(user -> user.isActive());

assertThat(user).isInstanceOf(User.class)
  .as(User.class)
  .isValid(userPredicate);
----

The `assertThat(..)` DSL operator provides many more capabilities out-of-the-box.

[[elements-lang-dsl-assertThat-exceptions]]
==== `assertThat` operator for Exceptions

The Elements `org.cp.elements.lang.ThrowableAssertions` class provides assertions for common Exceptions
thrown by application code:

* `assertThatArrayIndexOutOfBoundsException()`
* `assertThatIllegalArgumentException()`
* `assertThatIllegalStateException()`
* `assertThatIndexOutOfBoundsException()`
* `assertThatInterruptedException()`
* `assertThatNullPointerException()`
* `assertThatRuntimeException()`
* `assertThatSecurityException()`
* `assertThatUnsupportedOperationException()`

If your asserted Exception is not conveniently provided by a DSL, you can generically use:

* `assertThatThrowableOfType(:Class<? extends Throwable>)`

Even though Exception assertions were inspired by AssertJ as well, Elements Exception assertions enable assertion
chaining in the event that the application code throws a chained Exception. This enables developers to write
more expression Exception assertions:

.Chained Exception assertions
[source,java]
[subs="verbatim,attributes"]
----
assesrtThatThrowableOfType(UnauthroizedUserException.class)
  .isThrownBy(args -> applicationCodeThrowingSecurityException(unauthorizedUser))
  .havingMessage("User [%s] is not authorized", unauthorizedUser)
  .causedBy(SecurityException.class)
  .havingMessage("Security access exception occurred")
  .withNoCause();
----

When the `causeBy(:Class<? extends Throwable>)` method is called, it switches the assertion context to
the targeted Exception.

[[elements-lang-dsl-from]]
==== `from` operator

The `from` operator and DSL enables a developer to _cast_ or _convert_ from one type of object
to another type of object.

.Casting
[source,java]
[subs="verbatim,attributes"]
----
var numericObjectReference = 2;

Integer two = from(numericObjectReference).castTo(Integer.class);
----

.Converting
[source,java]
[subs="verbatim,attributes"]
----
Double number = from("123.45").convertTo(Double.class);
----

Under-the-hood, the `from` operator uses _Elements_ powerful Conversion library to perform the conversion.

Additionally, given a `java.util.function.Function`, developers may map an `Object` from 1 type to another:

.Mapping
[source,java]
[subs="verbatim,attributes"]
----
User jonDoe = from("jonDoe").mapTo(username -> User.as(username));
----

[[elements-lang-dsl-given]]
==== `given` operator

The `given` operator and DSL enables developers to declare "_expectations_" for an object,
satisfying certain conditions or requirements.

.Given
[source,java]
[subs="verbatim,attributes"]
----
User jonDoe = ...;

boolean result = given(jonDoe)
  .expectThat(jonDoe::isAuthenticated)
  .expectThat(jonDoe::isActive)
  .thenGiven(jonDoe::getGroups)
  .expectThat(jonDoeGroups -> jonDoeGroups.contains(Group.AUTHORIZED_USER))
  .result();
----

Alternatively, you can throw on a failed expectation.

.Given
[source,java]
[subs="verbatim,attributes"]
----
User jonDoe = ...;

given(jonDoe)
  .expectThat(jonDoe::isActive)
  .expectThat(jonDoe::isAuthenticated)
  .throwOnFailedExpectations()
  .thenGiven(jonDoe::getGroups)
  .expectThat(jonDoeGroups -> jonDoeGroups.contains(Group.AUTHORIZED_USER))
  .throwOnFailedExpectations();
----

`given` is a null-safe operator.

[[elements-lang-dsl-is]]
==== `is` operator

The `is` operator and DSL enables developers to perform conditional tests on an object or expression.

.Is
[source,java]
[subs="verbatim,attributes"]
----
boolean result = is(objectReference).notNull();
----

For more complex conditional tests, you can pass in a `java.util.function.Predicate`:

.Is using Predicate
[source,java]
[subs="verbatim,attributes"]
----
boolean result = is(objectReference).valid(:Prediate);
----

It is easy to negate the expression using the `not()` function:

.Is Not
[source,java]
[subs="verbatim,attributes"]
----
boolean result = is(objectReference).not().sameAs(otherObjectReference);
----

Conveniently, the `is` operator offers shortcuts for some of the negated conditional expressions:

.Is Not
[source,java]
[subs="verbatim,attributes"]
----
boolean result = is(objectReference).notSameAs(otherObjectReference);
----

[[elements-lang-design-patterns]]
=== Software Design Patterns as Code

In this section, we highlight several of Element's
https://en.wikipedia.org/wiki/Software_design_pattern[Software Design Patterns] as Code.

While Elements uses many different _Software Design Patterns_ in the library's implementation, the library
defines specific types to represent design patterns commmonly used in software development.

[[elements-lang-design-patterns-abstract-factory]]
==== Abstract Factory Pattern

Elements defines the `ObjectFactory` interface modeled after
the https://en.wikipedia.org/wiki/Abstract_factory_pattern[Abstract Factory Software Design Pattern]

.Builder interface
[source,java]
[subs="verbatim,attributes"]
----
inteface ObjectFactory<T> {
    <T> T create(objectTypeName, Object... args);
    <T> T create(objectTypeName, Class<?>[] paramterTypes, Object... args);
    <T> T create(Class<?> objectType, Object... args);
    <T> T create(Class<?> objectType, Class<?>[] paramterTypes, Object... args);
}
----

With an `ObjectFactory`, you can construct any family of objects, such as automobiles.

[[elements-lang-design-patterns-builder]]
==== Builder Pattern

Elements defines the `Builder` interface modeled after
the https://en.wikipedia.org/wiki/Builder_pattern[Builder Software Design Pattern].

.Builder interface
[source,java]
[subs="verbatim,attributes"]
----
interface Builder<T> {
    T build();
}
----

A `Builder` allows for the construction logic of a complex object to be encapsulated in a specialized,
implementing object.

[[elements-lang-design-patterns-composite]]
==== Composite Pattern

Elements defines the `Composite` interface modeled after
the https://en.wikipedia.org/wiki/Composite_pattern[Composite Software Design]. Pattern

.Composite interface
[source,java]
[subs="verbatim,attributes"]
----
interface Composite<T> {
    T composite(T one, T two);
}
----

The `Composite` allows multiple, similar objects all implementing a common interface to be treated as a single instance.

A `Composite` can be composed from an array or an `Iterable<T>` using:

.Composing objects
[source,java]
[subs="verbatim,attributes"]
----
Compsite<User> users = Composite.of(User.as("JonDoe"), User.as("JaneDoe"));

Composite<Action> actions = Composite.of(List.of(Action.as("load"), Action.as("save")));
----

[[elements-lang-design-patterns-dao]]
==== Data Access Object (DAO) Pattern

Elements models the Data Access Pattern (DAO) object implementing basic CRUD [ Create, Read, Update, Delete ]
as well as simple query operations on persistent entities.

Elements includes the `org.cp.elements.dao.DaoTemplate` class for executing basic CRUD and simple query operations.

[[elements-lang-design-patterns-proxy]]
==== Proxy Pattern

Elements defines the `ProxyFactory` class to construct JDK Dynamic Proxies from interface to model
the https://en.wikipedia.org/wiki/Proxy_pattern[Proxy Software Design Pattern].

.ProxyFactory abstract class
[source,java]
[subs="verbatim,attributes"]
----
interface ProxyFactory<T> {
  T newProxy(..);
}
----

The `ProxyFactory` is part a Service Provider Interface (SPI) provided by Elements using the `ProxyService` class.
So, while Elements uses JDK Dynamic Proxies by default, any type of object proxy can be plugged into the framework
using the SPI.

[[elements-lang-design-patterns-visitor]]
==== Visitor Pattern

Elements defines the `Visitor` interface modeled after
the https://en.wikipedia.org/wiki/Visitor_pattern[Visitor Software Design Pattern].

.Visitor interface
[source,java]
[subs="verbatim,attributes"]
----
interface Visitor {
    visit(Visitable object);
}
----

A `Visitor` walks the object graph of an object hierarchy to perform some operation on objects in the graph.

To compliment the `Visitor` interface, the `Visitable` interface defines objects that can be visited by a `Visitor`.

.Visitable interface
[source,java]
[subs="verbatim,attributes"]
----
interface Visitable {
    accept(Visitor visitor);
}
----
